{
    "openapi": "3.0.0",
    "info": {
        "title": "API Documentation",
        "description": "Langkah-langkah untuk melakukan tes API\n * 1. Register \n * 2. Login\n * 3. Setelah login,copy token yang di dapat lalu masukkan ke dalam bearer yang ada pada logo gembok\n * 4. setelahnya bisa melakukan tes API\n *\n * REKOMENDASI\n * 1. Create Category\n * 2. Create Buku\n * 3. Setelahnya bisa dilakukan testing fitur-fitur yang lain",
        "version": "1.0.0"
    },
    "paths": {
        "/api/register": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Register new user",
                "operationId": "8a56853624e025573120a09a4c75d468",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "no_induk": {
                                        "type": "string",
                                        "example": "12345"
                                    },
                                    "name": {
                                        "type": "string",
                                        "example": "John Doe"
                                    },
                                    "email": {
                                        "type": "string",
                                        "example": "john.doe@example.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "password123"
                                    },
                                    "is_admin": {
                                        "type": "boolean",
                                        "example": false
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "User created successfully."
                    },
                    "422": {
                        "description": "Validation failed."
                    },
                    "500": {
                        "description": "Server error."
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Login user",
                "operationId": "a3b306d14572d1f4bd6c064b3233e7b8",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "no_induk": {
                                        "type": "string",
                                        "example": "12345"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "password123"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Login successful."
                    },
                    "401": {
                        "description": "Invalid login credentials."
                    },
                    "422": {
                        "description": "Validation failed."
                    },
                    "500": {
                        "description": "Server error."
                    }
                }
            }
        },
        "/api/{model}/list": {
            "get": {
                "tags": [
                    "API Documentation Dinamis"
                ],
                "summary": "Mendapatkan daftar data dari model dinamis",
                "description": "Model yang tersedia adalah \n     * 1. Buku\n     * 2. Category\n     * 3. Pinjam\n     * 4. Kembali\n     * 5. User",
                "operationId": "getList",
                "parameters": [
                    {
                        "name": "model",
                        "in": "path",
                        "description": "Nama model (misalnya: buku, user)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data ditemukan",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string",
                                            "example": "Data Ditemukan"
                                        },
                                        "data": {
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Data tidak ditemukan"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/{model}/{id}/show": {
            "get": {
                "tags": [
                    "API Documentation Dinamis"
                ],
                "summary": "Mendapatkan detail data dari model dinamis",
                "description": "Model yang tersedia adalah \n     * 1. Buku\n     * 2. Category\n     * 3. Pinjam\n     * 4. Kembali\n     * 5. User",
                "operationId": "getShow",
                "parameters": [
                    {
                        "name": "model",
                        "in": "path",
                        "description": "Nama model (misalnya: buku, user)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID data",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data ditemukan"
                    },
                    "404": {
                        "description": "Data tidak ditemukan"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/{model}/create": {
            "post": {
                "tags": [
                    "API Documentation Dinamis"
                ],
                "summary": "Membuat data baru pada model dinamis",
                "description": "Model yang tersedia adalah \n * 1. Buku\n * 2. Category\n * 3. Pinjam\n * 4. Kembali\n * 5. User",
                "operationId": "createData",
                "parameters": [
                    {
                        "name": "model",
                        "in": "path",
                        "description": "Nama model (misalnya: buku, user)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "title": "Buku",
                                        "description": "Skema untuk membuat buku baru.",
                                        "properties": {
                                            "title": {
                                                "type": "string",
                                                "example": "Judul Buku"
                                            },
                                            "isbn": {
                                                "type": "string",
                                                "example": "B-001"
                                            },
                                            "author": {
                                                "type": "string",
                                                "example": "Nama Pengarang"
                                            },
                                            "publish_date": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-01-01"
                                            },
                                            "category": {
                                                "type": "integer",
                                                "example": 1
                                            },
                                            "image": {
                                                "type": "string",
                                                "format": "binary"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "Category",
                                        "description": "Skema untuk membuat category baru.",
                                        "properties": {
                                            "name": {
                                                "type": "string",
                                                "example": "Action"
                                            },
                                            "description": {
                                                "type": "string",
                                                "example": "Deskripsi kategori Action"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "Pinjam",
                                        "description": "Skema untuk membuat peminjaman baru.",
                                        "properties": {
                                            "id_buku": {
                                                "type": "integer",
                                                "example": 1
                                            },
                                            "id_user": {
                                                "type": "integer",
                                                "example": 5
                                            },
                                            "tgl_pinjam": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-03-13"
                                            },
                                            "tgl_kembali": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-03-20"
                                            },
                                            "status": {
                                                "type": "string",
                                                "example": "Dipinjam"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "Kembali",
                                        "description": "Skema untuk mencatat pengembalian buku.",
                                        "properties": {
                                            "id_buku": {
                                                "type": "integer",
                                                "example": 1
                                            },
                                            "id_user": {
                                                "type": "integer",
                                                "example": 5
                                            },
                                            "id_pinjam": {
                                                "type": "integer",
                                                "example": 10
                                            },
                                            "tgl_kembali": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-03-20"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "User",
                                        "description": "Skema untuk membuat pengguna baru.",
                                        "properties": {
                                            "name": {
                                                "type": "string",
                                                "example": "John Doe"
                                            },
                                            "no_induk": {
                                                "type": "string",
                                                "example": "123456"
                                            },
                                            "email": {
                                                "type": "string",
                                                "example": "johndoe@example.com"
                                            },
                                            "password": {
                                                "type": "string",
                                                "example": "password123"
                                            },
                                            "is_admin": {
                                                "type": "boolean",
                                                "example": false
                                            },
                                            "image": {
                                                "type": "string",
                                                "format": "binary"
                                            }
                                        },
                                        "type": "object"
                                    }
                                ]
                            },
                            "examples": {
                                "Buku": {
                                    "summary": "Contoh request untuk Buku",
                                    "value": {
                                        "title": "Judul Buku",
                                        "isbn": "B-001",
                                        "author": "Nama Pengarang",
                                        "publish_date": "2024-01-01",
                                        "category": 1,
                                        "image": "string"
                                    }
                                },
                                "Category": {
                                    "summary": "Contoh request untuk Category",
                                    "value": {
                                        "name": "Action",
                                        "description": "Deskripsi kategori action"
                                    }
                                },
                                "Pinjam": {
                                    "summary": "Contoh request untuk Pinjam",
                                    "value": {
                                        "id_buku": 1,
                                        "id_user": 5,
                                        "tgl_pinjam": "2024-03-13",
                                        "tgl_kembali": "2024-03-20"
                                    }
                                },
                                "Kembali": {
                                    "summary": "Contoh request untuk Kembali",
                                    "value": {
                                        "id_buku": 1,
                                        "id_user": 5,
                                        "id_pinjam": 10,
                                        "tgl_kembali": "2024-03-20"
                                    }
                                },
                                "User": {
                                    "summary": "Contoh request untuk User",
                                    "value": {
                                        "name": "John Doe",
                                        "no_induk": "123456",
                                        "email": "johndoe@gmail.com",
                                        "password": "password123",
                                        "is_admin": false,
                                        "image": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Data berhasil dibuat"
                    },
                    "400": {
                        "description": "Validasi gagal"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/{model}/{id}/update": {
            "put": {
                "tags": [
                    "API Documentation Dinamis"
                ],
                "summary": "Memperbarui data pada model dinamis",
                "description": "Model yang tersedia adalah \n * 1. Buku\n * 2. Category\n * 3. Pinjam\n * 4. Kembali\n * 5. User",
                "operationId": "updateData",
                "parameters": [
                    {
                        "name": "model",
                        "in": "path",
                        "description": "Nama model (misalnya: buku, user)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID data",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "title": "Buku",
                                        "description": "Skema untuk memperbarui buku.",
                                        "properties": {
                                            "title": {
                                                "type": "string",
                                                "example": "Judul Buku Baru"
                                            },
                                            "isbn": {
                                                "type": "string",
                                                "example": "B-002"
                                            },
                                            "author": {
                                                "type": "string",
                                                "example": "Nama Pengarang Baru"
                                            },
                                            "publish_date": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-02-01"
                                            },
                                            "category": {
                                                "type": "integer",
                                                "example": 2
                                            },
                                            "image": {
                                                "type": "string",
                                                "format": "binary"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "Category",
                                        "description": "Skema untuk memperbarui kategori.",
                                        "properties": {
                                            "name": {
                                                "type": "string",
                                                "example": "Adventure"
                                            },
                                            "description": {
                                                "type": "string",
                                                "example": "Deskripsi kategori Adventure"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "Pinjam",
                                        "description": "Skema untuk memperbarui peminjaman.",
                                        "properties": {
                                            "id_buku": {
                                                "type": "integer",
                                                "example": 2
                                            },
                                            "id_user": {
                                                "type": "integer",
                                                "example": 6
                                            },
                                            "tgl_pinjam": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-03-15"
                                            },
                                            "tgl_kembali": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-03-22"
                                            },
                                            "status": {
                                                "type": "string",
                                                "example": "Diperpanjang"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "Kembali",
                                        "description": "Skema untuk memperbarui pengembalian buku.",
                                        "properties": {
                                            "id_buku": {
                                                "type": "integer",
                                                "example": 2
                                            },
                                            "id_user": {
                                                "type": "integer",
                                                "example": 6
                                            },
                                            "id_pinjam": {
                                                "type": "integer",
                                                "example": 11
                                            },
                                            "tgl_kembali": {
                                                "type": "string",
                                                "format": "date",
                                                "example": "2024-03-22"
                                            }
                                        },
                                        "type": "object"
                                    },
                                    {
                                        "title": "User",
                                        "description": "Skema untuk memperbarui pengguna.",
                                        "properties": {
                                            "name": {
                                                "type": "string",
                                                "example": "Jane Doe"
                                            },
                                            "no_induk": {
                                                "type": "string",
                                                "example": "654321"
                                            },
                                            "email": {
                                                "type": "string",
                                                "example": "janedoe@example.com"
                                            },
                                            "password": {
                                                "type": "string",
                                                "example": "newpassword123"
                                            },
                                            "is_admin": {
                                                "type": "boolean",
                                                "example": true
                                            },
                                            "image": {
                                                "type": "string",
                                                "format": "binary"
                                            }
                                        },
                                        "type": "object"
                                    }
                                ]
                            },
                            "examples": {
                                "Buku": {
                                    "summary": "Contoh request untuk Buku",
                                    "value": {
                                        "title": "Judul Buku Baru",
                                        "isbn": "B-002",
                                        "author": "Nama Pengarang Baru",
                                        "publish_date": "2024-02-01",
                                        "category": 2,
                                        "image": "string"
                                    }
                                },
                                "Category": {
                                    "summary": "Contoh request untuk Category",
                                    "value": {
                                        "name": "Adventure",
                                        "description": "Deskripsi kategori Adventure"
                                    }
                                },
                                "Pinjam": {
                                    "summary": "Contoh request untuk Pinjam",
                                    "value": {
                                        "id_buku": 2,
                                        "id_user": 6,
                                        "tgl_pinjam": "2024-03-15",
                                        "tgl_kembali": "2024-03-22",
                                        "status": "Diperpanjang"
                                    }
                                },
                                "Kembali": {
                                    "summary": "Contoh request untuk Kembali",
                                    "value": {
                                        "id_buku": 2,
                                        "id_user": 6,
                                        "id_pinjam": 11,
                                        "tgl_kembali": "2024-03-22"
                                    }
                                },
                                "User": {
                                    "summary": "Contoh request untuk User",
                                    "value": {
                                        "name": "Jane Doe",
                                        "no_induk": "654321",
                                        "email": "janedoe@example.com",
                                        "password": "newpassword123",
                                        "is_admin": true,
                                        "image": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Data berhasil diperbarui"
                    },
                    "400": {
                        "description": "Validasi gagal"
                    },
                    "404": {
                        "description": "Data tidak ditemukan"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/{model}/{id}/delete": {
            "delete": {
                "tags": [
                    "API Documentation Dinamis"
                ],
                "summary": "Menghapus data dari model dinamis",
                "description": "Model yang tersedia adalah \n     * 1. Buku\n     * 2. Category\n     * 3. Pinjam\n     * 4. Kembali\n     * 5. User",
                "operationId": "deleteData",
                "parameters": [
                    {
                        "name": "model",
                        "in": "path",
                        "description": "Nama model (misalnya: buku, user)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID data",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data berhasil dihapus."
                    },
                    "404": {
                        "description": "Data tidak ditemukan."
                    },
                    "500": {
                        "description": "Terjadi kesalahan server."
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/{model}/{id}/denda": {
            "post": {
                "tags": [
                    "API Documentation Denda Buku"
                ],
                "summary": "Membayar denda pengembalian",
                "description": "Endpoint untuk membayar denda pengembalian buku.",
                "operationId": "bayarDenda",
                "parameters": [
                    {
                        "name": "model",
                        "in": "path",
                        "description": "Nama model (harus 'kembali')",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID pengembalian",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "jumlah_bayar": {
                                        "type": "number",
                                        "format": "float",
                                        "example": 5000
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Pembayaran denda berhasil."
                    },
                    "400": {
                        "description": "Validasi gagal."
                    },
                    "404": {
                        "description": "Data tidak ditemukan."
                    },
                    "500": {
                        "description": "Terjadi kesalahan server."
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Authentication",
            "description": "Authentication"
        },
        {
            "name": "API Documentation Dinamis",
            "description": "API Documentation Dinamis"
        },
        {
            "name": "API Documentation Denda Buku",
            "description": "API Documentation Denda Buku"
        }
    ]
}